template:
  - binary_sensor:
      - name: "Bathroom Occupancy 1m"
        state: >
          {{ is_state('binary_sensor.bathroom_lumi_lumi_motion_ac02_motion', 'on') }}
        delay_off:
          minutes: 1
  
  - binary_sensor:
      - name: "Sitting at desk Occupancy"
        state: >
          {{ is_state('binary_sensor.presence_sensor_fp2_1446_presence_sensor_2', 'on') }}
        delay_on:
          minutes: 2
        delay_off:
          minutes: 4
  
  - binary_sensor:
      - name: "Hallway Occupancy 30s"
        state: >
          {{ is_state('binary_sensor.lumi_lumi_motion_ac02_iaszone_2', 'on') }}
        delay_off:
          seconds: 30